version: '3.8'

services:
  postgresql:
    image: postgres:16.2
    container_name: postgresql
    restart: "always"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - devops-network

  flowable-rest:
    image: flowable/flowable-rest
    container_name: flowable-rest
    restart: "always"
    env_file:
      - .env      
    ports:
      - "18080:8080" # DEPLOY_ENV
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 0s
    networks:
      - devops-network
    depends_on:
      - postgresql

networks:
  devops-network:
    external: true
