version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: "always"
    env_file:
      - .env
    command: ["server", "/data", "--console-address", ":9001"]
    # https://github.com/minio/minio/issues/18389
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ./data:/data
    networks:
      - devops-network

networks:
  devops-network:
    external: true
