version: '3.8'

# TODO: add health check
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: "always"
    env_file:
      - .env
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    networks:
      - devops-network

networks:
  devops-network:
    external: true
