version: '3.8'

services:
  liquibase:
    image: liquibase/liquibase:4.32
    container_name: liquibase
    restart: unless-stopped
    privileged: true
    volumes:
      - ./changelog:/liquibase/changelog
    # ports:
    networks:
      - devops-network
    command: tail -f /dev/null
    # command: >
    #   --url=jdbc:mysql://mysql:3306/archery
    #   --username=root
    #   --password=devops+mysql
    #   --changeLogFile=/liquibase/changelog.xml
    #   update

networks:
  devops-network:
    external: true