version: '3.8'

services:
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: "always"
    ports:
      - 8686:8686
    volumes:
      - ./conf/vector.yaml:/etc/vector/vector.yaml
      - ./logs:/etc/vector/logs
    networks:
      - devops-network

  # source
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    restart: "always"
    ports:
    - 18080:8080
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./logs:/var/log # output log
    networks:
      - devops-network

  # sink
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    restart: "always"
    env_file:
      - .env
    ports:
      - 8123:8123 # HTTP
      - 9000:9000 # native
    volumes:
      - clickhouse:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      # - ./user_files:/var/lib/clickhouse/user_files
    command: "${CLICKHOUSE_ARGS}"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - devops-network

  bytebase:
    image: bytebase/bytebase:2.14.1
    container_name: bytebase
    restart: "always"
    ports:
      - 18081:8080
    volumes:
      - ./bytebase:/var/opt/bytebase
    networks:
      - devops-network

networks:
  devops-network:
    external: true

volumes:
  clickhouse:
    external: true
  clickhouse-logs:
    external: true