# https://github.com/bitnami/containers/tree/main/bitnami/spark

version: '3.8'

services:
  spark:
    image: bitnami/spark:3.5
    container_name: spark
    restart: "always"
    env_file:
      - .env.master
    ports:
      - 7077:7077 # for master
      - 18080:8080 # web UI for master
      - 14040:4040 # application web UI
      - 16066:6066 # master REST API
      - 15002:15002 # Spark Connect Server
    volumes:
    #   - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    #   - ./data:/bitnami/spark
      - ./mysql-connector-j-8.0.32.jar:/opt/bitnami/spark/jars/mysql-connector-j-8.0.32.jar
    networks:
      - devops-network

  spark-worker:
    image: bitnami/spark:3.5
    # container_name: spark-worker
    restart: "always"
    env_file:
      - .env.worker
    volumes:
    #   - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    #   - ./data:/bitnami/spark
      - ./mysql-connector-j-8.0.32.jar:/opt/bitnami/spark/jars/mysql-connector-j-8.0.32.jar
    ports:
      - 18081-18082:8081 # web UI for worker
    networks:
      - devops-network

networks:
  devops-network:
    external: true