version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    restart: "always"
    env_file:
      - .env
    ports:
    - 6831:6831/udp # agent: jaeger.thrift
    - 6832:6832/udp # agent: jaeger.thrift for Node.js
    - 5778:5778 # agent: configs
    - 16686:16686 # query
    - 4317:4317 # collector: OpenTelemetry over gRPC
    - 4318:4318 # collector: OpenTelemetry over HTTP
    - 14250:14250 # collector: model.proto
    - 14268:14268 # collector: jaeger.thrift
    - 14269:14269
    - 9411:9411 # collector: Zipkin
    networks:
      - devops-network

networks:
  devops-network:
    external: true
