version: '3'

services:
  redis:
    image: redis:5
    container_name: redis
    restart: always
    command: redis-server --requirepass devops+redis
    expose:
      - "6379"
    networks:
      - ops-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/my.cnf:/etc/my.cnf"
      - "./mysql/data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: archery
      # DEPLOY_ENV
      MYSQL_ROOT_PASSWORD: devops+mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - ops-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  goinception:
    image: hanchuanchuan/goinception
    container_name: goinception
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - "./inception/config.toml:/etc/config.toml"
    networks:
      - ops-network

  archery:
    image: hhyo/archery:v1.12.0
    container_name: archery
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "9123:9123"
    volumes:
      - "./archery/settings.py:/opt/archery/local_settings.py"
      - "./archery/soar.yaml:/etc/soar.yaml"
      - "./archery/docs.md:/opt/archery/docs/docs.md"
      - "./archery/downloads:/opt/archery/downloads"
      - "./archery/sql/migrations:/opt/archery/sql/migrations"
      - "./archery/logs:/opt/archery/logs"
      - "./archery/keys:/opt/archery/keys"
      - "./archery/sqlserver.sh:/opt/archery/sqlserver.sh" # SQL Server
      - "./.env:/opt/archery/.env"
      # custom code
      # - "./archery/custom/mongo.py:/opt/archery/sql/engines/mongo.py"
      # - "./archery/custom/archiver.py:/opt/archery/sql/archiver.py"
    entrypoint: "bash /opt/archery/src/docker/startup.sh"
    env_file:
      - .env
    networks:
      - ops-network

networks:
  ops-network:
    external: true
