version: "3.8"
services:
  # Usually on application machines.
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    container_name: filebeat
    restart: always
    user: root
    volumes: # DEPLOY_ENV
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - apm-network
    environment:
      - "strict.perms=false"
    # depends_on:
    #   - apm-es

networks:
  apm-network:
    external: true
