# https://raw.githubusercontent.com/conductor-oss/conductor/main/docker/docker-compose-mysql.yaml
version: '3.8'

services:

  # Commented for local running
  conductor-server:
    container_name: conductor-server
    image: conductor:server
    # DEPLOY_DEV: local build
    # build:
    #   context: ./conductor
    #   dockerfile: ./docker/server/Dockerfile
    # docker hub
    # image: conductoross/conductor:3.15.0
    env_file:
      - .env
    networks:
      - devops-network
    ports:
      - 8080:8080
      - 5000:5000
    volumes: # DEPLOY_DEV: local build hack
      - ./conductor/server/build/libs/conductor-server-boot.jar:/app/libs/conductor-server.jar
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - conductor-elasticsearch:es
      - conductor-mysql:mysql
      - conductor-redis:rs
    depends_on:
      conductor-elasticsearch:
        condition: service_healthy
      conductor-mysql:
        condition: service_healthy
      conductor-redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-mysql:
    image: mysql:8.0.36
    container_name: conductor-mysql
    env_file:
      - .env
    volumes:
      - type: volume
        source: conductor_mysql
        target: /var/lib/mysql
    networks:
      - devops-network
    ports:
      - 3306:3306
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/3306'
      interval: 5s
      timeout: 5s
      retries: 12

  conductor-redis:
    image: redis:6.2.3-alpine
    container_name: conductor-redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - devops-network
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  conductor-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: conductor-elasticsearch
    env_file:
      - .env
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - devops-network
    ports:
      - 9200:9200
    healthcheck:
      test: curl http://localhost:9200/_cluster/health -o /dev/null
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.11
    container_name: conductor-kibana
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: # DEPLOY_ENV
      - 5601:5601
    networks:
      - devops-network
    depends_on:
      - conductor-elasticsearch

volumes:
  conductor_mysql:
    driver: local
  esdata-conductor:
    driver: local

networks:
  devops-network:
    external: true