version: '3.8'

services:
  nginx:
    image: nginx:1.27.3
    container_name: nginx
    restart: "always"
    ports:
      - 18080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - devops-network

  # Prometheus Exporter
  # https://github.com/nginx/nginx-prometheus-exporter
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    container_name: nginx-exporter
    restart: "always"
    ports:
      - 19113:9113
    command:
      - --nginx.scrape-uri=http://nginx:80/basic_status
    networks:
      - devops-network

networks:
  devops-network:
    external: true
