version: "3.8"
services:
  # Usually on application machines.
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.11
    container_name: filebeat
    restart: unless-stopped
    user: root
    volumes: # DEPLOY_ENV
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - //var/lib/docker/containers:/var/lib/docker/containers:ro
      - //var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - devops-network
    command: "-strict.perms=false"
    # entrypoint: ["tail", "-f", "/dev/null"]

networks:
  devops-network:
    external: true
