version: '3.8'

services:
  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    restart: "always"
    env_file:
      - .env
    ports:
      - 61613:61613
      - 61616:61616
      - 18161:8161 # DEPLOY_ENV: conflict with Docker Desktop Backend
    volumes:
      - ./data:/var/lib/artemis-instance
    networks:
      - devops-network

networks:
  devops-network:
    external: true
