version: '3.8'

services:
  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    restart: "always"
    env_file:
      - .env
    ports:
      - 61616:61616 # AMQP, STMOP, MQTT, OpenWire
      - 5672:5672 # AMQP
      - 61613:61613 # STMOP
      - 1883:1883 # MQTT
      - 18161:8161 # console, DEPLOY_ENV: conflict with Docker Desktop Backend
    volumes:
      - ./data:/var/lib/artemis-instance
    networks:
      - devops-network

networks:
  devops-network:
    external: true
