version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:2.20.2-alpine
    container_name: portainer
    restart: "always"
    ports:
      - 18000:8000
      - 19000:9000
      - 19443:9443
    volumes:
      - portainer_data:/data
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-network

networks:
  devops-network:
    external: true

volumes:
  portainer_data:
    external: true