version: "3.8"
services:
  apm-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: apm-es
    restart: always
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports: # DEPLOY_ENV
      - 19200:9200
    networks:
      - apm-network
    environment: # DEPLOY_ENV
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: # DEPLOY_ENV
      - 15601:5601
    networks:
      - apm-network
    depends_on:
      - apm-es

networks:
  apm-network:
    external: true
