version: '3.8'

services:
  zoo1:
    image: zookeeper:3.9.3
    restart: always
    hostname: zoo1
    networks:
      - devops-network
    ports:
      - 2181:2181 # client port
    environment:
      ZOO_MY_ID: 1
      # server.x=[hostname]:nnnnn[:nnnnn]
      # x: server number
      # 2888: for followers to connect to leader
      # 3888: for leader election
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper:3.9.3
    restart: always
    hostname: zoo2
    networks:
      - devops-network
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper:3.9.3
    restart: always
    hostname: zoo3
    networks:
      - devops-network
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zookezoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    restart: "unless-stopped"
    # entrypoint: "tail -f /dev/null"
    networks:
      - devops-network
    ports:
      - 9000:9000

networks:
  devops-network:
    external: true
