version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    restart: unless-stopped
    privileged: true
    env_file:
      - .env
    volumes:
    - ./data/data:/var/opt/mssql/data
    - ./data/log:/var/opt/mssql/log
    - ./data/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
    networks:
      - devops-network
    # setup: https://github.com/microsoft/mssql-docker/tree/master/linux/preview/examples/mssql-customize

networks:
  devops-network:
    external: true