version: "3.8"
services:
  # https://skywalking.apache.org/docs/main/latest/readme/
  skywalking-oap-server:
    image: apache/skywalking-oap-server:10.1.0
    container_name: skywalking-oap-server
    restart: always
    env_file:
      - .env
    ports: # DEPLOY_ENV
      - 11800:11800 # gRPC
      - 12800:12800 # HTTP
    networks:
      - apm-network 
    # volumes: # MySQL
      # - ./mysql-connector-java-5.1.49.jar:/skywalking/oap-libs/mysql-connector-java-5.1.49.jar
    depends_on:
      - banyandb

  # https://skywalking.apache.org/docs/skywalking-banyandb/latest/readme/
  banyandb:
    image: apache/skywalking-banyandb:0.7.1
    container_name: banyandb
    command: ["standalone"]
    restart: always
    ports: # DEPLOY_ENV
      - 17912:17912 # gRPC
      - 17913:17913 # HTTP
    networks:
      - apm-network   

  skywalking-ui:
    image: apache/skywalking-ui:10.1.0
    container_name: skywalking-ui
    restart: always
    ports: # DEPLOY_ENV
      - 18080:8080
    networks:
      - apm-network 
    environment: # DEPLOY_ENV
      - "JAVA_OPTS=-Xms128m -Xms128m"
      - "SW_OAP_ADDRESS=http://skywalking-oap-server:12800"
    depends_on:
      - skywalking-oap-server



networks:
  apm-network:
    external: true
