version: '3.8'

# ports: https://rocketmq-learning.com/faq/ons-user-question-history16530/

services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: namesrv
    command: sh mqnamesrv
    ports:
      - 9876:9876
    networks:
      - devops-network

  broker:
    image: apache/rocketmq:5.3.2
    container_name: broker
    command: sh mqbroker
    ports:
      - 10909:10909 # VIPChannel
      - 10911:10911 # listenPort
      - 10912:10912 # haListenPort
    environment:
      - NAMESRV_ADDR=namesrv:9876
    networks:
      - devops-network
    depends_on:
      - namesrv

  proxy:
    image: apache/rocketmq:5.3.2
    container_name: proxy
    command: sh mqproxy
    restart: on-failure
    ports:
      - 18080:18080 # Remoting
      - 18081:18081 # gRPC
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      # https://github.com/apache/rocketmq/blob/develop/proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java
      - ./rmq-proxy.json:/home/rocketmq/rocketmq-5.3.2/conf/rmq-proxy.json
    networks:
      - devops-network
    depends_on:
      - broker
      - namesrv

  dashboard:
    image: apacherocketmq/rocketmq-dashboard
    container_name: dashboard
    command: sh mqproxy
    restart: on-failure
    ports:
      - 18082:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876
    networks:
      - devops-network
    depends_on:
      - namesrv  

networks:
  devops-network:
    external: true