version: '3.8'

services:
  kafka-broker:
    image: apache/kafka:3.7.0
    container_name: kafka-broker
    restart: "always"
    ports:
      - 9092:9092
      - 8161:8161 
    volumes:
      # - ./server.properties:/opt/kafka/config/server.properties
      - ./data:/tmp/kraft-combined-logs
    networks:
      - devops-network

networks:
  devops-network:
    external: true
