version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: "always"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - devops-network

networks:
  devops-network:
    external: true
