version: '3.8'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: "always"
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/var/lib/registry
    networks:
      - devops-network

networks:
  devops-network:
    external: true
