version: '3.8'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: xxl-job-admin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 18080:8080
    volumes:
      - ./applogs:/data/applogs
    networks:
      - devops-network

  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: "always"
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 0s
    networks:
      - devops-network

networks:
  devops-network:
    external: true